FROM node
WORKDIR /usr/src/app
ENV API_URL=http://api-mock:8083
ENV PUBLIC_PATH=/familie/sykdom-i-familien/soknad/overfore-omsorgsdager

COPY . .
#RUN apk update && apk add bash && apk add curl

RUN CYPRESS_INSTALL_BINARY=0 npm ci
RUN npm run build
EXPOSE 8084
CMD ["npm", "run", "server-test"]
