# See .env for default ENV vars
version: '3.7'
services:
  api-mock:
    build: ../server
    environment:
      - "PORT=8089"
    ports:
      - 8089:8089
  web:
    build:
      context: ../
      dockerfile: Dockerfile.web-cypress
    ports:
      - 8084:8084
    depends_on:
      - api-mock
