apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
    name: overfore-omsorgsdager
    namespace: default
    labels:
        team: dusseldorf
spec:
    image: {{ image }}
    port: 8080
    liveness:
        path: /familie/sykdom-i-familien/soknad/overfore-omsorgsdager/health/isAlive
        initialDelay: 20
        timeout: 1
        periodSeconds: 5
        failureThreshold: 10
    readiness:
        path: /familie/sykdom-i-familien/soknad/overfore-omsorgsdager/health/isReady
        initialDelay: 20
        timeout: 1
    resources:
        limits:
            cpu: 2000m
            memory: 512Mi
        requests:
            cpu: 50m
            memory: 128Mi
    ingresses:
        - https://www-q0.nav.no/familie/sykdom-i-familien/soknad/overfore-omsorgsdager
        - https://overfore-omsorgsdager.nais.oera-q.local
    replicas:
        min: 1
        max: 1
        cpuThresholdPercentage: 90
    prometheus:
        enabled: true
        path: /metrics
    vault:
        enabled: false
    env:
        - name: APPRES_CMS_URL
          value: http://appres.nav.no
        - name: API_URL
          value: https://omsorgsdageroverforingsoknad-api-q.nav.no
        - name: PUBLIC_PATH
          value: /familie/sykdom-i-familien/soknad/overfore-omsorgsdager
        - name: LOGIN_URL
          value: https://loginservice-q.nav.no/login?redirect=https://www-q0.nav.no/familie/sykdom-i-familien/soknad/overfore-omsorgsdager/melding
        - name: APPSTATUS_PROJECT_ID
          value: "ryujtq87"
        - name: APPSTATUS_DATASET
          value: "staging"


